# This is a basic workflow to help you get started with Actions

name: NPU test

# Controls when the workflow will run
on:
  push:
  workflow_dispatch:


jobs:
  build:
    runs-on: hx370

    steps:
      - uses: actions/checkout@v4

      - name: Check NPU visibility
        run: /opt/xilinx/xrt/bin/xrt-smi examine --report all

      - name: Run NPU validation check
        run: /opt/xilinx/xrt/bin/xrt-smi validate --verbose

      - name: Build and run MLIR-AIE example
        run: |
          . /mlir-aie/ironenv/bin/activate
          . /mlir-aie/utils/env_setup.sh

          git clone https://github.com/Xilinx/mlir-aie mlir-aie
          cd mlir-aie/programming_examples/basic/passthrough_kernel
          make
          make run
