# This is a basic workflow to help you get started with Actions

name: self hosted test

# Controls when the workflow will run
on:
  push:
  workflow_dispatch:


jobs:
  build:
    runs-on: hx370

    steps:
      - uses: actions/checkout@v4

      - name: Check NPU visibility
        run: xrt-smi examine

      - name: Check GPU visibility
        run: amd-smi list

      - name: Check existing files and create one
        run: |
          ls -lhat
          touch $(date +%s).txt
